name: "Pre: Plan"

on:
  pull_request:

jobs:
  pre:
    if: github.event.pull_request.base.ref == github.event.repository.default_branch &&
        github.event.repository.is_template == false
    name: "Pre: Plan"
    runs-on: ubuntu-latest
