name: "Update"

on:
  workflow_call:

jobs:
  update:
    name: "Update"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout GitHub Management template
        uses: actions/checkout@v2
        with:
          repository: protocol/github-mgmt-template
          path: github-mgmt-template
      - name: Checkout GitHub Management
        uses: actions/checkout@v2
        with:
          path: github-mgmt
      - name: Copy files from the template
        run: |
          for file in $(git ls-files .github scripts terraform .gitignore -- . ':!:terraform/resources_override.tf'); do
            cp -f "$file" "../github-mgmt/$file"
          done
        working-directory: github-mgmt-template
      - uses: ./.github/actions/git-config-user
      - run: |
          git add --all
          git diff-index --quiet HEAD || git commit --message='update (#${{ github.run_number }})'
        working-directory: github-mgmt
      - uses: ./.github/actions/git-push
        with:
          suffix: update
          working-directory: github-mgmt
